### ISSUE TITLE
problems with migration remove

### ISSUE THREAD

**Issue by belforte** [dmwm/dbs2go#76] opened 2022-08-24 22:39 UTC
this [1] appears to stall unitl eventually front end forces HTTP 502 and that migration id is still there.

But when I tried again I got HTTP 200 and migration is now gone.

should we be concerned ? Is the http 502 somehow due to load in the server ? 

[1]
```
belforte@lxplus8s03/migration> cat mig_request.json 
{"migration_rqst_id": 3311328}
belforte@lxplus8s03/migration> 
belforte@lxplus8s03/migration> 
belforte@lxplus8s03/migration> 
belforte@lxplus8s03/migration> 
belforte@lxplus8s03/migration> X5curl -v -H "Content-Type: application/json" -d@$PWD/mig_request.json   https://cmsweb-prod.cern.ch:8443/dbs/prod/phys03/DBSMigrate/remove
*   Trying 137.138.157.32...
* TCP_NODELAY set
* Connected to cmsweb-prod.cern.ch (137.138.157.32) port 8443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: DC=ch; DC=cern; OU=computers; CN=cmsweb-prod.cern.ch
*  start date: Feb 17 12:51:44 2022 GMT
*  expire date: Mar 24 12:51:44 2023 GMT
*  subjectAltName: host "cmsweb-prod.cern.ch" matched cert's "cmsweb-prod.cern.ch"
*  issuer: DC=ch; DC=cern; CN=CERN Grid Certification Authority
*  SSL certificate verify ok.
> POST /dbs/prod/phys03/DBSMigrate/remove HTTP/1.1
> Host: cmsweb-prod.cern.ch:8443
> User-Agent: curl/7.59.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 30
> 
* upload completely sent off: 30 out of 30 bytes


< HTTP/1.1 502 Bad Gateway
< Date: Wed, 24 Aug 2022 22:29:45 GMT
< Server: Apache
< Set-Cookie: cms-auth=57da255fcb85ec0c8b178d24d6fd13b866d74d10d742e4b4bed2b50491bbab17884df48c93cdd4cf;path=/;secure;httponly;expires=Thu, 01-Jan-1970 00:00:01 GMT
< Content-Type: text/html
< Content-Length: 150
< CMS-Server-Time: D=193904896 t=1661379991096829
< 
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host cmsweb-prod.cern.ch left intact
belforte@lxplus8s03/migration> 


```

**Comment by belforte** [comment] 2022-08-25 12:50
here's another example from this morning, this one keeps failing
```
belforte@lxplus8s03/migration> cat mig_request.json 
{"migration_rqst_id": 3326851}
belforte@lxplus8s03/migration> time X5curl -v -H "Content-Type: application/json" -d@$PWD/mig_request.json   https://cmsweb-prod.cern.ch:8443/dbs/prod/phys03/DBSMigrate/remove
*   Trying 137.138.157.32...
* TCP_NODELAY set
* Connected to cmsweb-prod.cern.ch (137.138.157.32) port 8443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: DC=ch; DC=cern; OU=computers; CN=cmsweb-prod.cern.ch
*  start date: Feb 17 12:51:44 2022 GMT
*  expire date: Mar 24 12:51:44 2023 GMT
*  subjectAltName: host "cmsweb-prod.cern.ch" matched cert's "cmsweb-prod.cern.ch"
*  issuer: DC=ch; DC=cern; CN=CERN Grid Certification Authority
*  SSL certificate verify ok.
> POST /dbs/prod/phys03/DBSMigrate/remove HTTP/1.1
> Host: cmsweb-prod.cern.ch:8443
> User-Agent: curl/7.59.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 30
> 
* upload completely sent off: 30 out of 30 bytes
< HTTP/1.1 504 Gateway Time-out
< Date: Thu, 25 Aug 2022 08:58:40 GMT
< Server: Apache
< Set-Cookie: cms-auth=6f43a86c72376cb56ad251cd404775aa0fcb0735acdbcf52ac39bcb0ca74b950a3102f9c5ad310da;path=/;secure;httponly;expires=Thu, 01-Jan-1970 00:00:01 GMT
< Content-Type: text/html
< Content-Length: 160
< CMS-Server-Time: D=300062108 t=1661417620869709
< 
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host cmsweb-prod.cern.ch left intact

real	5m0.142s
user	0m0.031s
sys	0m0.028s
belforte@lxplus8s03/migration>
```

**Comment by belforte** [comment] 2022-08-25 12:53
on a new attempt the remove above failed instad with HTTP 502 after 2'27" [1]

we have many blocks which failed to be migrated with old server because of the problem with configuration, but now I can't remove those migration ids and when trying to submit again I get (rightfully) 

 Error: migration request /QCD_Pt-30To50_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2/MINIAODSIM#2874f0ba-5ae4-410b-ac37-c09c5b1f1810 is already exist in DB

[1]
```
belforte@lxplus8s03/migration> cat mig_request.json 
{"migration_rqst_id": 3326851}
belforte@lxplus8s03/migration> date
Thu Aug 25 14:49:27 CEST 2022
belforte@lxplus8s03/migration> time X5curl -v -H "Content-Type: application/json" -d@$PWD/mig_request.json   https://cmsweb-prod.cern.ch:8443/dbs/prod/phys03/DBSMigrate/remove
*   Trying 137.138.157.32...
* TCP_NODELAY set
* Connected to cmsweb-prod.cern.ch (137.138.157.32) port 8443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: DC=ch; DC=cern; OU=computers; CN=cmsweb-prod.cern.ch
*  start date: Feb 17 12:51:44 2022 GMT
*  expire date: Mar 24 12:51:44 2023 GMT
*  subjectAltName: host "cmsweb-prod.cern.ch" matched cert's "cmsweb-prod.cern.ch"
*  issuer: DC=ch; DC=cern; CN=CERN Grid Certification Authority
*  SSL certificate verify ok.
> POST /dbs/prod/phys03/DBSMigrate/remove HTTP/1.1
> Host: cmsweb-prod.cern.ch:8443
> User-Agent: curl/7.59.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 30
> 
* upload completely sent off: 30 out of 30 bytes
< HTTP/1.1 502 Bad Gateway
< Date: Thu, 25 Aug 2022 12:51:57 GMT
< Server: Apache
< Set-Cookie: cms-auth=8d86dcfc59c706a8720e10f64386142dccc2bca356ae87a9a34d5eaf3228b1d7296b16453950692a;path=/;secure;httponly;expires=Thu, 01-Jan-1970 00:00:01 GMT
< Content-Type: text/html
< Content-Length: 150
< CMS-Server-Time: D=147662966 t=1661431769550131
< 
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host cmsweb-prod.cern.ch left intact

real	2m27.748s
user	0m0.035s
sys	0m0.014s
belforte@lxplus8s03/migration> 

```

**Comment by belforte** [comment] 2022-08-25 13:05
FWIW, I traced this request in DBSMigrate log 
after removeing the Prometheus and kube-ctl lines I found this snippet
```
[2022-08-25 08:27:41.524277352 +0000 UTC m=+2354.021404541] handlers.go:514: API=remove params=map[]
 createBy=/DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte 
belforte@infn.it separator=','
[2022-08-25 08:27:41.524929057 +0000 UTC m=+2354.022056247] utils.go:265: execute
[2022-08-25 08:27:41.525164175 +0000 UTC m=+2354.022291400] utils.go:269: ### SQL statement ###
SELECT count(*) AS count FROM cms_dbs3_prod_phys03_owner.MIGRATION_REQUESTS
WHERE MIGRATION_REQUEST_ID=:migration_rqst_id
      and (migration_status=0 or migration_status=3 or migration_status=9)

[2022-08-25 08:27:41.525348032 +0000 UTC m=+2354.022475222] utils.go:274: ### SQL values ###
        '3326851'

[2022-08-25 08:27:41.526263702 +0000 UTC m=+2354.023390891] migrate.go:1426: found 1 records to remo
ve for request ID 3326851
[2022-08-25 08:35:33.628371571 +0000 UTC m=+2826.125498750] validator.go:129: StrPatern check key=bl
ock_name val=/DoubleMuon/Run2018A-15Feb2022_UL2018-v1/MINIAOD#a8908eb2-e5bb-4188-9f3b-dba06de1cfac
[2022-08-25 08:35:33.62872526 +0000 UTC m=+2826.125852436] validator.go:130: patterns [^/[a-zA-Z][a-
zA-Z0-9\-_]+/[a-zA-Z0-9\.\-_]+/[A-Z\-_]+#[a-zA-Z0-9\.\-_]+] max length 402
[2022-08-25 08:35:33.628923566 +0000 UTC m=+2826.126050744] validator.go:350: query parameter key=bl
ock_name values=[/DoubleMuon/Run2018A-15Feb2022_UL2018-v1/MINIAOD#a8908eb2-e5bb-4188-9f3b-dba06de1cf
ac]
[2022-08-25 08:35:33.629369515 +0000 UTC m=+2826.126496693] parameters.go:74: DBS status API is not 
presented in ApiParamMap

```

**Comment by belforte** [comment] 2022-08-25 13:06
thanks Valenting. I believe that you can submit the request yourself as well, I do not know if there is a check on DN anymore. Let me know if/how I may help.

**Comment by vkuznet** [comment] 2022-08-25 13:53
Stefano, it seems to me the issue is with ORACLE DB owner which can't delete records using the account we use. I looked at migration requests with status=9 and we have 14K of them. Then, I login to DB with writer account and call the following query:
```
SQL> delete from cms_dbs3_prod_phys03_owner.MIGRATION_REQUESTS where migration_request_id=185533;
```
and it stuck over there. This explain why we see timeouts. I need to review writer account permissions and contact DBA. So far please stop removal of requests until you'll hear from me.

**Comment by belforte** [comment] 2022-08-25 13:58
But I do not think we made 14K such requests in last weeks. Maybe in python server remove of migration does something different from deleting record from Oracle ? Should I try to use DBSMigrate python version (which I think is running) to remove those failed migrations, see what happens ? Maybe ti will simply remove link from block name to migration ID opening up for creation of a new one ?

**Comment by vkuznet** [comment] 2022-08-25 14:03
No, you will be surprised but these 14K are dated by 2014. I think python server never deleted them due to DB issue.

**Comment by vkuznet** [comment] 2022-08-25 14:04
Here is one record I tried to remove manually in DB using writer accoutn:
```
create_by             : slava77
creation_date         : 1405679240
last_modification_date: 1405679684
last_modified_by      : slava77
migration_input       : /MinBias_TuneZ2star_14TeV-pythia6/TTI2023Upg14-DES23_62_V1-v1/GEN-SIM#88bab590-d1c4-11e3-904b-00221959e69e
migration_request_id  : 185373
create_by             : slava77
creation_date         : 1405679279
last_modification_date: 1405679927
last_modified_by      : slava77
migration_input       : /MinBias_TuneZ2star_14TeV-pythia6/TTI2023Upg14-DES23_62_V1-v1/GEN-SIM#ff4a8592-d1a0-11e3-904b-00221959e69e
migration_request_id  : 185533
migration_server      : <nil>
migration_status      : 9
migration_url         : https://cmsweb.cern.ch/dbs/prod/global/DBSReader
retry_count           : 3

```
and its creation date refers to
```
>>> import time
>>> time.gmtime(1405679279)
time.struct_time(tm_year=2014, tm_mon=7, tm_mday=18, tm_hour=10, tm_min=27, tm_sec=59, tm_wday=4, tm_yday=199, tm_isdst=0)
```

**Comment by belforte** [comment] 2022-08-25 14:05
yet, old DBS python code had some way to report to status query "migration id not found" and let a new migration request to be created, which is all we care about, we simply want to be free to retry with new code !

**Comment by belforte** [comment] 2022-08-25 14:06
in other words it may have been intentional to leave those DB records there, that's all I am saying.

**Comment by vkuznet** [comment] 2022-08-25 14:09
can we discuss the issue on skype or zoom? I'm in WMCore room: https://cern.zoom.us/j/3939207009?pwd=Q2JMOWd0L3NKZy9ITGsyWlZhaTMwZz09 and if you can connect it would be easier to discuss what needs to be done.

**Comment by vkuznet** [comment] 2022-08-25 14:49
Stefano, I checked DBS python codebase and it has the same queries as I placed in Go one, see
https://github.com/dmwm/DBS/blob/master/Server/Python/src/dbs/dao/Oracle/MigrationRequests/Remove.py#L29

So, the python code does the following:
- select migration request
- delete migration request
see https://github.com/dmwm/DBS/blob/master/Server/Python/src/dbs/dao/Oracle/MigrationRequests/Remove.py#L23-L32

And, GO server does the same, see
count migration requests 
https://github.com/dmwm/dbs2go/blob/master/dbs/migrate.go#L1411
and its associative query
https://github.com/dmwm/dbs2go/blob/master/static/sql/count_migration_requests.sql
and then remove migration request
https://github.com/dmwm/dbs2go/blob/master/dbs/migrate.go#L1430
and its associative query
https://github.com/dmwm/dbs2go/blob/master/static/sql/remove_migration_requests.sql

SO, from code inspection both servers will do the same queries.

**Comment by belforte** [comment] 2022-08-25 15:15
for some obscure reasons I can not remove migrations with old code.
I only tried one ID, am very slow in these days, will try more, but this is very strange. Logs offer no useful info:
```
INFO:cherrypy.access:[25/Aug/2022:17:03:56] dbs-migrate-55d7d54487-jv6wj 137.138.157.32 "GET /dbspy/prod/phys03/DBSMigrate/status?migration_rqst_id=3326851 HTTP/1.1" 200 OK [data: 1357 in 646 out 9692 us ] [auth: OK "/DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte belforte@infn.it" "" ] [ref: "" "DBSClient/Unknown/" ]
ERROR:dbs.web.DBSMigrateModel:Thu Aug 25 15:05:34 2022 dbsException-invalid-input2: (400, 'DBSMigration: Invalid request. Sucessfully processed or processing requests cannot be removed,                    or the requested migration did not exist, or the requestor for removing and creating has to be the same user. ')
Traceback (most recent call last):
  File "/data/srv/HG2209a/sw/slc7_amd64_gcc630/cms/dbs3/3.16.0-comp5/lib/python2.7/site-packages/dbs/web/DBSMigrateModel.py", line 131, in remove
    return self.dbsMigrate.removeMigrationRequest(indata)
  File "/data/srv/HG2209a/sw/slc7_amd64_gcc630/cms/dbs3/3.16.0-comp5/lib/python2.7/site-packages/dbs/business/DBSMigrate.py", line 294, in removeMigrationRequest
    self.mgrremove.execute(conn, migration_rqst)
  File "/data/srv/HG2209a/sw/slc7_amd64_gcc630/cms/dbs3/3.16.0-comp5/lib/python2.7/site-packages/dbs/dao/Oracle/MigrationRequests/Remove.py", line 51, in execute
    dbsExceptionHandler('dbsException-invalid-input', msg, self.logger.exception)
  File "/data/srv/HG2209a/sw/slc7_amd64_gcc630/cms/dbs3/3.16.0-comp5/lib/python2.7/site-packages/dbs/utils/dbsExceptionHandler.py", line 16, in dbsExceptionHandler
    raise HTTPError(400, message)
HTTPError: (400, 'DBSMigration: Invalid request. Sucessfully processed or processing requests cannot be removed,                    or the requested migration did not exist, or the requestor for removing and creating has to be the same user. ')
INFO:cherrypy.access:[25/Aug/2022:17:05:34] dbs-migrate-55d7d54487-jv6wj 137.138.157.32 "POST /dbspy/prod/phys03/DBSMigrate/remove HTTP/1.1" 400 Bad Request [data: 30 in 287 out 4103 us ] [auth: OK "/DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte belforte@infn.it" "" ] [ref: "" "DBSClient/Unknown/" ]

```
but this 3326851 is a request created with same DN
```
[{'create_by': '/DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica '
               'Nucleare/CN=Stefano Belforte belforte@infn.it',
  'creation_date': 1661380825,
  'last_modification_date': 1661381255,
  'last_modified_by': '/DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di '
                      'Fisica Nucleare/CN=Stefano Belforte belforte@infn.it',
  'migration_input': '/QCD_Pt-30To50_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2/MINIAODSIM#2874f0ba-5ae4-410b-ac37-c09c5b1f1810',
  'migration_request_id': 3326851,
  'migration_server': 'dbs2go-phys03-migration-864f857f6f-4plnt',
  'migration_status': 9,
  'migration_url': 'https://cmsweb-prod.cern.ch/dbs/prod/global/DBSReader',
  'retry_count': 4}]
```

**Comment by belforte** [comment] 2022-08-25 15:17
thanks for having checked code. We are sort of stuck here. If Kate is away you can write to oracle support at CERN and some other DBAs will have a look, usually good people. But surely Kate knows a lot about our stuff which they don't.

**Comment by belforte** [comment] 2022-08-25 15:18
hmm I see that the migId which I was trying to remove was created by 'migration_server': 'dbs2go-phys03-migration-864f857f6f-4plnt' , let me try one created by old server, sorry.

**Comment by vkuznet** [comment] 2022-08-25 15:35
I created CERN ticket too, see https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC3219679

**Comment by vkuznet** [comment] 2022-08-25 15:51
Steafno, could you please join zoom room again, the same URL https://cern.zoom.us/j/3939207009?pwd=Q2JMOWd0L3NKZy9ITGsyWlZhaTMwZz09 that we can discuss response from Oracle CERN ticket I think we need to shutdown py and one of the go servers to avoid racing conditions across three deployments

**Comment by vkuznet** [comment] 2022-08-25 16:16
Stefano, in order to perform clean-up we need to shutdown migration servers. I can shutdown Go ones but I do not have access to python one and Muhammad seems is not online now. Please let me know if I can shutdown Go servers and then I can try to run manual query on DB side to see if it will finish cleanup. Or, we should wait till Muhammad will be back online to shutdown all servers.

**Comment by belforte** [comment] 2022-08-25 16:18
Valentin, fine with me. CRAB Publisher is a stupid, persistent beast and will keep retrying. No problem.

**Comment by belforte** [comment] 2022-08-25 16:19
Many publications do no need migrations and will go on in the meanwhile.

**Comment by vkuznet** [comment] 2022-08-25 16:29
so, turns out Muhammad turn off python migration server, this explain why you cannot use it. So, we will stop now Go servers and stop python one, then I'll do manual clean-up and then we will restart Go serve, is it ok with you?

**Comment by vkuznet** [comment] 2022-08-25 17:40
Stefano, I made few tests and indeed clean-up query we use takes full table scan and may take hours to complete. Before making full clean-up I sent email to Yuyi asking about her feedback and you are in CC. Meanwhile, we restored DBSMigrate/DBSMigration on cmsweb-prod clusters and all other servers are not reacheable. My suggestion to wait for Yuyi's feebback and then do the following:
- delete all failed migration requests with status=9, those 14K dated way back to 2014
- discuss how to clean-up successful migration request, we have 2.5M of them and again to clean them up we need downtime and I need to understand from Yuyi is it appropriate to do
- after that we can discuss how to proceed, e.g. discuss with DBA how to speed up clean-up query, etc.

So, now one Go server set (DBSMigrate and DBSMigration) is running on cmsweb-prod such that CRAB can proceed with migration, but clean-up will most likely kill pods and if you'll submit remove request it will fail with timeout. I do not want to change things drastically until we get more information.

**Comment by belforte** [comment] 2022-08-25 19:36
sorry I had to leave. Yes it was/is OK. I thought that migration request removal only involved DBSMIgrate not migration server as well... Oh well, I should never assume too much !

thank for the update and the hard work. But IIUC cleanup is something which we should have done anyhow, did not etc. etc., so nothing which affects us in the immediate. And imaybe there is a way to make it happen in the background even if slowly (i.e.even if it takes a month) w/o a downtime ?

I have not understood if cleanup is still running or now. I.e. if I can remove failed migrations which should be attempted again.
W/o hurry, kindly let me know.

**Comment by belforte** [comment] 2022-08-25 19:47
well. I will hardly be able to do anything until late tomorrow anyhow

**Comment by vkuznet** [comment] 2022-08-25 20:18
Stefano, the clean-up can be done in background if we'll first dump all migration ids, and then use them in single delete query. Since there is an index on migration request id the delete of single migration request id will be quick, but since we have almost 700K of them and associative 2.5M blocks it will take time. Said that, I still want to get in touch with Yuyi and Kate before making any changes or run manual procedure.

Meanwhile, if you know you rmigration ids which needs to be deleted I can manually delete them in DB. Just send me ids.

**Comment by yuyiguo** [comment] 2022-08-25 21:30
I don't my email as much as before because all the experiments are on Slack. 
This is the first time I heard that a permanently failed migration couldn't be removed from the DB. If I recall correctly, the crab had scripts to remove the failed ones. DBS python did not remove anything from DB unless the user asked. This was DB policy. If a migration failed, the user created had to remove it before the person could send another.

**Comment by yuyiguo** [comment] 2022-08-25 21:42
In the email, you said you could not remove a failed migration using the writer account. You have all the owner accounts and you can check the permission. I haven't touched anything in past one-half year and all I can say is the migration worked well before.

**Comment by yuyiguo** [comment] 2022-08-25 21:44
What is the status now? Which server is running? What is the current URL to access the migration server?

**Comment by yuyiguo** [comment] 2022-08-25 21:59
Regarding the indexes, operations on DBS migration python server were based on migration request id so we did not have the need to create other indexes in the past. In addition, indexes will take time to create when inserting a record. We aimed to speed up the migration so the less was better. If you think the Go server needs to have more indexes, feel free to create them.

In the past, the migration server rarely failed. Once in a while, some migration might fail, they would be removed immediately by Crab, then they can submit again. So, we did not have the needs to delete a bunch of bad ones at once.

what did happen so that a bunch of migration failed for crab?

**Comment by vkuznet** [comment] 2022-08-26 13:57
@yuyiguo , the issue raised due to this clean-up query:
```
DELETE FROM cms_dbs3_prod_phys03_owner.MIGRATION_REQUESTS WHERE
LAST_MODIFICATION_DATE <= 1653666269 or (migration_status=3 and
retry_count=3 and last_modification_date <= 1661391869) or
(migration_status=9 and retry_count=3 and last_modification_date <=
1661391869)
```
whose syntax I used from py server code to make clean-up. According to CERN DBA (Kate is out of office, so I opened SNOW ticket) this query performs full table scan. Therefore, it blocks entire table. As such any other delete query using `migration_rqst_id` were blocked. This is the actual issue. I do not know how python server performed clean-up, but the queries I took directly from python server code.

**Comment by vkuznet** [comment] 2022-08-26 14:00
@belforte , once I commented out cleanup migration server (which run within a goroutine, similar to python trhead), there is no longer the issue with removal. I was able to successfully deleted your request using the following set of curl comamnds:
```
lxplus8s03(15:53:01) cmsweb ⎈ cmsweb-testbed-v1.22.9 > scurl https://cmsweb-prod.cern.ch:8443/dbs/prod/phys03/DBSMigrate/status?migration_rqst_id=3326851
[
{"create_by":"/DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte belforte@infn.it","creation_date":1661380825,"last_modification_date":1661381255,"last_modified_by":"/DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte belforte@infn.it","migration_input":"/QCD_Pt-30To50_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2/MINIAODSIM#2874f0ba-5ae4-410b-ac37-c09c5b1f1810","migration_request_id":3326851,"migration_server":"dbs2go-phys03-migration-864f857f6f-4plnt","migration_status":9,"migration_url":"https://cmsweb-prod.cern.ch/dbs/prod/global/DBSReader","retry_count":4}
]
lxplus8s03(15:53:11) cmsweb ⎈ cmsweb-testbed-v1.22.9 >
lxplus8s03(15:53:42) cmsweb ⎈ cmsweb-testbed-v1.22.9 > scurl -v -H "Content-Type: application/json" -d'{"migration_rqst_id": 3326851}' https://cmsweb-prod.cern.ch:8443/dbs/prod/phys03/DBSMigrate/remove
*   Trying 137.138.157.32...
* TCP_NODELAY set
* Connected to cmsweb-prod.cern.ch (137.138.157.32) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: DC=ch; DC=cern; OU=computers; CN=cmsweb-prod.cern.ch
*  start date: Feb 17 12:51:44 2022 GMT
*  expire date: Mar 24 12:51:44 2023 GMT
*  issuer: DC=ch; DC=cern; CN=CERN Grid Certification Authority
*  SSL certificate verify ok.
> POST /dbs/prod/phys03/DBSMigrate/remove HTTP/1.1
> Host: cmsweb-prod.cern.ch:8443
> User-Agent: curl/7.61.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 30
>
* upload completely sent off: 30 out of 30 bytes
< HTTP/1.1 200 OK
< Date: Fri, 26 Aug 2022 13:53:47 GMT
< Server: Apache
< Set-Cookie: cms-auth=5b45882e684e7fb3ff6f6937340acb1a974dcb289afe2cbc56a118306d79b6ecd8fce0c175e8bcc5;path=/;secure;httponly;expires=Thu, 01-Jan-1970 00:00:01 GMT
< Content-Type: application/json
< Content-Length: 0
< X-Ratelimit-Limit: 100
< X-Ratelimit-Remaining: 99
< X-Ratelimit-Reset: 1661522028
< CMS-Server-Time: D=302343 t=1661522027100970
<
* Connection #0 to host cmsweb-prod.cern.ch left intact
lxplus8s03(15:53:47) cmsweb ⎈ cmsweb-testbed-v1.22.9 > scurl https://cmsweb-prod.cern.ch:8443/dbs/prod/phys03/DBSMigrate/status?migration_rqst_id=3326851
```
So, your migration request 3326851 is gone now, and I think this particular issue can be closed. Feel free to to try it out with another request.

Meanwhile, I'll discuss with CERN DBAs next week a proper set of actions and plan how to adjust clean-up query. For time being the clean-up server is not enabled and we can live with that for quite some time and manually perform clean-up of DB if necessary. And, this restored functionality of `/remove` API which is working now (at least within my tests).

**Comment by yuyiguo** [comment] 2022-08-26 15:20
@vkuznet , I don't understand your clean up query and why you need to do it while the DB is in production. I think the first thing we need to figure out is why we had a burst of migration failures in August to prevent future failures.

**Comment by vkuznet** [comment] 2022-08-26 16:20
@yuyi, I think it is my fault as may mis-understood the logic of python codebase. Somehow I was under impression that clean-up procedure was automatically done in python codebase.

Meanwhile, regarding failure of migration failures in Aug. Until I will knot more details about them, e.g. dates of injection, etc., it is hard to answer. One possible explanation is difference in data-format between old/new DBS server implementation. But again it is just a thought and without any details I can't say much.

Before putting new DBS Migration server in production we run tests and even run parallel injection from CRAB server. We spent almost 2 months with Stefano all details as I was not familiar with  them. And, I got a green light from both CRAB and WMCore team who performed tests in testbed before moving forward. The clean-up part seems to be oversight as this didn't show up in testbed (due to small size of DB and table content).

**Comment by belforte** [comment] 2022-08-27 14:06
@vkuznet sorry for a stupid question. As you know I had changed code to use blok_name instead of requestID for bookkeeping of migrations. Now we have O(400) failed migrations to ger rid of but my log has only the block name.
Is it safe to use that in the remove, or should I better get a migration ID via migrate/status first  ?

**Comment by vkuznet** [comment] 2022-08-27 17:10
@belforte , the `/remove` API only accepts `migration_rqst_id` parameter, if you need to support block_input or better `migration_input` I can add it but it will require code changes and testing. Let me know, and I may try to add it next week if it is required.

**Comment by belforte** [comment] 2022-08-27 17:52
no problem Valentin, I will get rqst_id and use it. Maybe I will even change back the code to use rqst_id for bookkeeping of which migrations to check, easier to copy/paste around than a block name ! And no need to worry about urlencoding the `#` char when using curl :-)

**Comment by belforte** [comment] 2022-08-28 20:07
small thing: IIUC DBSMigrate/remove API does not return anything when successful, this confuses DBSClient raises an exception:
```
The server output is not a valid json, most probably you have a typo in the url.
https://cmsweb-prod.cern.ch:8443/dbs/prod/phys03/DBSMigrate.
```
as per
https://github.com/dmwm/DBSClient/blob/be292dca5b82f72a8cf9bf13e7dc263232ab7b16/src/python/dbs/apis/dbsClient.py#L480-L484

Maybe server could return some json also here ?

**Comment by vkuznet** [comment] 2022-08-29 13:14
Stefano, I applied the change to production server. Now `remove` API upon success returns valid JSON. Please check and let me know if we can close this issue.

**Comment by belforte** [comment] 2022-08-29 15:32
remove API is fine now, thanks. And removal works.
We still have problems though. I will open a new issue. You can close this.

**Closed** 2022-08-29 16:26 UTC
